### PR TITLE
Fix Japanese localization

### PR DESCRIPTION
**Pull request by SKEIDs**

### CODE REVIEW

**Comment by joshuaseltzer** [comment]
Why did you revert the title back to English in the localization files?

**Comment by SKEIDs** [comment]
> Why did you revert the title back to English in the localization files?

I didn't expect it to be a string on the Youtube app settings. 
I don't think the title needs to be localized, just the name of the tweak.

**Comment by joshuaseltzer** [comment]
Well, all of the other items in the YouTube app settings are in the native language so I'd argue that it should remain localized. Also, the name of the tweak is actually "YTHoldForSpeed" but this item in the settings is just "Hold for speed" since it is just describing what settings can be changed.

If you'd still like to proceed with the PR we can, but I personally think it should remain translated.

**Comment by SKEIDs** [comment]
I see. I follow you.

**Pull request merged**
